{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.secretName" . }}
  namespace: {{ include "app.namespace" . }}
type: Opaque
stringData:
  {{- range $k, $v := .Values.secret.stringData }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}
